blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/orgs/digglelens/discussions
    about: For questions that are not bug reports or feature requests, please use Discussions.
